# -*- coding: utf-8 -*-
# Powered by Kanak Infosystems LLP.
# © 2020 Kanak Infosystems LLP. (<https://www.kanakinfosystems.com>).

{
    'name': 'Prescription',
    'version': '16.0.1.3',
    'author': 'Kanak Infosystems LLP.',
    'website': 'https://www.kanakinfosystems.com',
    'category': 'Hospital/Pharmacy',
    'license': 'OPL-1',
    'summary': 'Prescription Module is used to manage prescriptions and sale the prescribed medicine from pos | POS Prescription | Patient Prescription | Prescribe medicines',
    'description': "Prescription Module is used to create prescriptions and sale the prescribed medicines from the POS also, the user is able to create prescription order directly from the pos screen.",
    'depends': ['base', 'sale', 'point_of_sale', 'product', 'l10n_in', 'web', 'icd_manager', 'portal', 'canvas_image_editor', 'tus_meta_whatsapp_base'],
    'images': ['static/description/banner.jpg'],
    'data': [
        'security/record_rule.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/message.xml',
        'demo/product_product_demo.xml',
        'wizard/import_patient_xls.xml',
        'wizard/schedule_wizard.xml',
        'views/prescription_appointment.xml',
        'views/res_partner_view.xml',
        'views/prescription_order.xml',
        'views/prescription_template_view.xml',
        'views/pos_config_view.xml',
        'views/complaint_advice_views.xml',
        'views/product_product_inherit.xml',    
        'views/appointment_schedule.xml',
        'views/res_config_setting.xml',
        'views/referral_partner.xml',
        'views/account_move.xml',
        'views/radiology_request.xml',
        'views/res_prescription_portal_view.xml',
        'report/report_document_invoice.xml',
        'report/prescription_order_report.xml',
        'views/menuitems.xml',
        'views/configuration_view.xml',
        'report/prescription_report.xml',
        "report/radiology_report_template.xml",
    ],
    'assets': {
        'point_of_sale.assets': [
            'pos_prescription_knk/static/src/css/pos.css',
            'pos_prescription_knk/static/src/js/PODetail.js',
            'pos_prescription_knk/static/src/js/PrescriptionOrderScreen.js',
            'pos_prescription_knk/static/src/js/OpenPOButton.js',
            'pos_prescription_knk/static/src/js/EnablePreOrder.js',
            'pos_prescription_knk/static/src/js/PosOrder.js',
            'pos_prescription_knk/static/src/js/PrescriptionOrders.js',
            'pos_prescription_knk/static/src/js/pos_model.js',
            'pos_prescription_knk/static/src/xml/**/*',
        ],
    },
    'application': True,
    'price': 130,
    'currency': 'EUR',
}
